DROP TABLE users;
DROP TABLE views;
DROP TABLE votes;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  pwd VARCHAR(255) NOT NULL,
  registration DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS views (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  iduser INTEGER NOT NULL, -- Must point to users.id!
  idduck VARCHAR(255) NOT NULL,
  time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS votes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    iduser INTEGER NOT NULL, -- Must ponit to users.id!
    idduck INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);